### ISSUE TITLE
 Class 'Entrecore\GTMetrixClient\GTMetrixClient' not found

### ISSUE THREAD

**Issue by PetiteFlamme31** [entrecore/php-gtmetrix#11]
Hello,

Thanks you for your API but I have some problems...

I want to test in a php page this API but it doesn't work.

I have this : 
```
Warning: The use statement with non-compound name 'GTMetrixClient' has no effect in E:\xampp\htdocs\projets\Projet2\index.php on line 12

Fatal error: Uncaught Error: Class 'GTMetrixClient' not found in E:\xampp\htdocs\projets\Projet2\index.php:15 Stack trace: #0 {main} thrown in E:\xampp\htdocs\projets\Projet2\index.php on line 15
```

And my code is : 
```
<!DOCTYPE html>

<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
        <?php
        require('vendor/autoload.php');

        use Entrecore\GTMetrixClient\GTMetrixClient;
        use Entrecore\GTMetrixClient\GTMetrixTest;

        $client = new GTMetrixClient();
        $client->setUsername('***@***');
        $client->setAPIKey('***');

        $client->getLocations();
        $client->getBrowsers();
        $test = $client->startTest('**');

        //Wait for result
        while ($test->getState() != GTMetrixTest::STATE_COMPLETED &&
        $test->getState() != GTMetrixTest::STATE_ERROR) {
            $client->getTestStatus($test);
            sleep(5);
        }
        ?>
    </body>
</html>
```

Can you help me please ?
Thank you so much.

(_Sorry for my bad english_)

**Comment by ghost** [comment]
Hello @PetiteFlamme31 ,

This library is no longer maintained. Please use [philcook/gtmetrix](https://github.com/philcook/php-gtmetrix) instead.

**Comment by PetiteFlamme31** [comment]
Thanks for this informations but I think it's exacly what I have done, I have philcook/gtmetrix installed, I have installed composer in XAMPP and after that, with the command '' composer require philcook/gtmetrix'' I have installed this API in my project folder...

**Comment by ghost** [comment]
@PetiteFlamme31 as we no longer support this library, I recommend that you go over to Phil Cooks repo and raise the issue there. We, as a company, no longer have any PHP code in our infrastructure, we only host it.

**Comment by PetiteFlamme31** [comment]
I understand, thank you for your help !
Have a nice day.

**Comment by philcook** [comment]
@PetiteFlamme31 I believe this issue has been resolved on my repo but please do feel free to raise and issue on my repo if required [philcook/gtmetrix](https://github.com/philcook/php-gtmetrix)
